"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const Button_Button = require("./Button.js");
require("react-native");
require("../Ripple/index.js");
require("../utils.js");
require("../Ripple/Ripple.js");
require("react");
require("../Ripple/utils.js");
require("../Ripple/RippleElement.js");
require("../Ripple/Ripple.web.js");
exports.Button = Button_Button.Button;
